package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author
 */
public class AddCure extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

    public AddCure() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        dbCon = new myDBCon();
        
        lblMedicineName.setText("");
        lblDiseaseName.setText("");
            
        try {
            //populate combo boxes           

            // populate Patient ID combobox
            rs = dbCon.executeStatement("SELECT id, name FROM disease ORDER BY name ASC");
            while (rs.next()) {
               cmbDiseaseId.addItem(rs.getString("id"));
            }
            
            // populate medicine name combobox
            rs = dbCon.executeStatement("SELECT id,name FROM medicine ORDER BY name ASC");
            while (rs.next()) {
                cmbMedID.addItem(rs.getString("id"));
            }

            rs.close();
            
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jMedId7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        cmbDiseaseId = new javax.swing.JComboBox<>();
        cmbMedID = new javax.swing.JComboBox<>();
        btnAddNewEmp = new javax.swing.JButton();
        lblMedicineName = new javax.swing.JLabel();
        lblDiseaseName = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Cure");

        jMedId7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jMedId7.setText("Medicine ID:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Disease ID:");

        cmbDiseaseId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbDiseaseId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbDiseaseIdActionPerformed(evt);
            }
        });

        cmbMedID.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbMedID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedIDActionPerformed(evt);
            }
        });

        btnAddNewEmp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        lblMedicineName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblMedicineName.setText("medicine name");

        lblDiseaseName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDiseaseName.setText("disease name");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(148, 148, 148)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jMedId7)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbDiseaseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblDiseaseName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(cmbMedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lblMedicineName))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(btnAddNewEmp)))
                .addContainerGap(110, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jMedId7)
                    .addComponent(cmbMedID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMedicineName))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cmbDiseaseId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblDiseaseName))
                .addGap(26, 26, 26)
                .addComponent(btnAddNewEmp)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // clear all labels used to display error messages 
    void clearErrorLabels() { 
    }

    // validate all user entry before sending new patient details to DB
    boolean isValidData() throws SQLException {
        clearErrorLabels();
        boolean result = true;
        
        String field_medicine_name = cmbMedID.getSelectedItem().toString();
        String field_patient_name = cmbDiseaseId.getSelectedItem().toString();

        return result;
    }

    // clear for every new entry 
    void clearInputBoxes() { 
        cmbMedID.setSelectedIndex(0);
        cmbDiseaseId.setSelectedIndex(0);
    }

    private boolean isDuplicate(int medicine_id, int patient_id) throws SQLException {
        // check if cure id already exists
        String stmtSQL = "SELECT medicine_id, disease_id FROM cures WHERE medicine_id = " + medicine_id + "AND disease_id = " + patient_id;
        rs = dbCon.executeStatement(stmtSQL);
        return rs.isBeforeFirst();
    }
    
    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:

        try {
            if (isValidData()) {
                String field_medicine_name = cmbMedID.getSelectedItem().toString();
                String field_patient_name = cmbDiseaseId.getSelectedItem().toString();

                String prepSQL = "INSERT INTO cures (medicine_id, disease_id) VALUES ("
                        + "" + field_medicine_name + ", "
                        + "" + field_patient_name + " "
                        + ")";
                System.out.println("[INSERT Cure] " + prepSQL);

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("New cure added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                }

                rs.close();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new cure.");
        }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    private void cmbDiseaseIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbDiseaseIdActionPerformed
        // TODO add your handling code here:
        String diseaseId = cmbDiseaseId.getSelectedItem().toString();
        ResultSet rsLookup;
        try {
            rsLookup = dbCon.executeStatement("SELECT name FROM disease WHERE id = " + diseaseId);
            rsLookup.next();
            String diseaseName = rsLookup.getString("name");
            rsLookup.close();
            lblDiseaseName.setText("(" + diseaseName + ")");
        } catch (SQLException ex) {
            Logger.getLogger(AddCure.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_cmbDiseaseIdActionPerformed

    private void cmbMedIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedIDActionPerformed
        // TODO add your handling code here:
        String medicineId = cmbMedID.getSelectedItem().toString();
        ResultSet rsLookup;
        try {
            rsLookup = dbCon.executeStatement("SELECT name FROM medicine WHERE id = " + medicineId);
            rsLookup.next();
            String medicineName = rsLookup.getString("name");
            rsLookup.close();
            lblMedicineName.setText("(" + medicineName + ")");
        } catch (SQLException ex) {
            Logger.getLogger(AddCure.class.getName()).log(Level.SEVERE, null, ex);
        } 
    }//GEN-LAST:event_cmbMedIDActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JComboBox<String> cmbDiseaseId;
    private javax.swing.JComboBox<String> cmbMedID;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jMedId7;
    private javax.swing.JLabel lblDiseaseName;
    private javax.swing.JLabel lblMedicineName;
    // End of variables declaration//GEN-END:variables
}
