package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import static jdbcgui.AddEmployee.txtSSN;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author wissam
 */
public class AddDoctor extends javax.swing.JFrame {

    /**
     * Creates new form AddEmployee
     */
    myDBCon dbCon;
    ResultSet rs;
    
    
    public AddDoctor() {
        initComponents();
        //this.setLocationRelativeTo(null); // center form in screen 
        this.setLocation(WIDTH, HEIGHT);
        // set all error labels to invisible
        lblSpecializatoinError.setVisible(false);
        lblQualificationError.setVisible(false);
        dbCon = new myDBCon();
        cmbQualification.addItem("NONE");
        cmbQualification.addItem("MBBS");
        cmbQualification.addItem("MD");
        cmbQualification.addItem("DO");
        cmbQualification.addItem("BMBS");
        cmbQualification.addItem("MBChB");
        cmbQualification.addItem("MBBCh");
        cmbQualification.addItem("B.Med");
        cmbQualification.addItem("MB");
        cmbQualification.addItem("BM");
        cmbQualification.addItem("B.S");
        cmbQualification.addItem("B.Surg");
        cmbQualification.addItem("Dr.MuD");
        cmbQualification.addItem("Dr.Med");
        cmbQualification.addItem("DPM");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jSpecializatoin = new javax.swing.JLabel();
        jQualification = new javax.swing.JLabel();
        txtSpecialization = new javax.swing.JTextField();
        btnAddNewEmp = new javax.swing.JButton();
        lblSpecializatoinError = new javax.swing.JLabel();
        lblQualificationError = new javax.swing.JLabel();
        cmbQualification = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Doctor");

        jSpecializatoin.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jSpecializatoin.setText("Specialization:");

        jQualification.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jQualification.setText("Qualification:");

        txtSpecialization.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtSpecialization.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSpecializationActionPerformed(evt);
            }
        });

        btnAddNewEmp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        lblSpecializatoinError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblSpecializatoinError.setForeground(new java.awt.Color(255, 0, 0));
        lblSpecializatoinError.setText("error label");

        lblQualificationError.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblQualificationError.setForeground(new java.awt.Color(255, 0, 0));
        lblQualificationError.setText("error label");

        cmbQualification.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbQualification.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbQualificationActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jSpecializatoin)
                    .addComponent(jQualification))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblQualificationError, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblSpecializatoinError, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(220, 220, 220)
                        .addComponent(btnAddNewEmp))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(118, 118, 118)
                        .addComponent(jLabel1)))
                .addContainerGap(178, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jSpecializatoin)
                            .addComponent(txtSpecialization, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblSpecializatoinError)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jQualification)
                        .addComponent(lblQualificationError))
                    .addComponent(cmbQualification, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddNewEmp)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    void clearErrorLabels() { // clear all labels used to display error messages 
        lblSpecializatoinError.setText("");
        lblSpecializatoinError.setVisible(false);
        lblQualificationError.setText("");
        lblQualificationError.setVisible(false);
    }

    // validate all user entry before sending new employee details to DB
    boolean isValidData() {
        clearErrorLabels();
        boolean result = true; // assume all details are true, set to false if otherwise 
        // you need to check format deails and make sure they are consistent with DB 
        

        if (txtSpecialization.getText().trim().isEmpty() || (txtSpecialization.getText().trim().length() > 20)) {
            if (txtSpecialization.getText().trim().isEmpty()) {
                lblSpecializatoinError.setText("Invalid. Cannot be empty.");
            } else if ((txtSpecialization.getText().trim().length() > 10)) {
                lblSpecializatoinError.setText("Invalid. Must be < 30 chars.");
            }
            lblSpecializatoinError.setVisible(true);
            result = false;
        }

        

        return result;
    }

    void clearInputBoxes() { // clear for every new entry 
        txtSpecialization.setText("");
        cmbQualification.setSelectedIndex(0);
        txtSSN.setText("");
    }

    
    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:

        try {
            /*
                * you need also to verify that the empno is unique and not duplicate 
                  
                *
             */
            if (isValidData()) {
                // if new employee details are valid, then add new employee to DB
                String prepSQL = "INSERT INTO doctor (ssn, specialization, qualification) VALUES ("
                        + txtSSN.getText().trim() + ", "
                        + "'" + txtSpecialization.getText().toUpperCase() + "', "
                        + "'" + cmbQualification.getSelectedItem().toString() + "')";

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {

                    javax.swing.JLabel label = new javax.swing.JLabel("New doctor added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                } else {

                }

            } else {
                javax.swing.JLabel label = new javax.swing.JLabel("Please fix validation errors...");
                label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                JOptionPane.showMessageDialog(null, label, "ERROR", JOptionPane.ERROR_MESSAGE);
                 

            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new doctor.");
        }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    private void txtSpecializationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSpecializationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSpecializationActionPerformed

    private void cmbQualificationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbQualificationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbQualificationActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JComboBox<String> cmbQualification;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jQualification;
    private javax.swing.JLabel jSpecializatoin;
    private javax.swing.JLabel lblQualificationError;
    private javax.swing.JLabel lblSpecializatoinError;
    private javax.swing.JTextField txtSpecialization;
    // End of variables declaration//GEN-END:variables
}
