package jdbcgui;

import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author 
 */
public class AddTakes extends javax.swing.JFrame {

    myDBCon dbCon;
    ResultSet rs;

    public AddTakes() {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 
        // set all error labels to invisible
        lblErrorPatientId.setVisible(false);
        lblErrorMedicineId.setVisible(false);
        lblErrorDosePerDay.setVisible(false);

        dbCon = new myDBCon();
            
        try {
            //populate combo boxes 
            // populate medicine id combobox
            rs = dbCon.executeStatement("SELECT id FROM medicine ORDER BY id ASC");
            while (rs.next()) {
                cmbMedicineId.addItem(rs.getString("id"));
            }
            
            // populate patient id combobox
            rs = dbCon.executeStatement("SELECT id FROM patient ORDER BY id ASC");
            while (rs.next()) {
                cmbPatientId.addItem(rs.getString("id"));
            }
            
            rs.close();
            
        } catch (SQLException e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtDosePerDay = new javax.swing.JTextField();
        cmbMedicineId = new javax.swing.JComboBox<>();
        cmbPatientId = new javax.swing.JComboBox<>();
        btnAddNewEmp = new javax.swing.JButton();
        lblErrorPatientId = new javax.swing.JLabel();
        lblErrorMedicineId = new javax.swing.JLabel();
        lblErrorDosePerDay = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add New Employee");
        setResizable(false);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel1.setText("Add New Take");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Patient ID:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Medicine ID:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Dose per Day:");

        txtDosePerDay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        cmbMedicineId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        cmbMedicineId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbMedicineIdActionPerformed(evt);
            }
        });

        cmbPatientId.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        btnAddNewEmp.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        btnAddNewEmp.setText("Add New");
        btnAddNewEmp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewEmpActionPerformed(evt);
            }
        });

        lblErrorPatientId.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblErrorPatientId.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorPatientId.setText("error label");

        lblErrorMedicineId.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblErrorMedicineId.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorMedicineId.setText("error label");

        lblErrorDosePerDay.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        lblErrorDosePerDay.setForeground(new java.awt.Color(255, 0, 0));
        lblErrorDosePerDay.setText("error label");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 122, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(cmbMedicineId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorMedicineId, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtDosePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblErrorDosePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(225, 225, 225)
                        .addComponent(btnAddNewEmp)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(lblErrorPatientId)
                    .addComponent(cmbPatientId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblErrorMedicineId)
                    .addComponent(cmbMedicineId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDosePerDay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorDosePerDay))
                .addGap(18, 18, 18)
                .addComponent(btnAddNewEmp)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // verify valid entry of integer values
    public boolean isInteger(String s) {
        try {
            Integer.parseInt(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // verify valid entry of double values
    public boolean isDouble(String s) {
        try {
            Double.parseDouble(s);
            return true;
        } catch (NumberFormatException ex) {
            return false;
        }
    }

    // clear all labels used to display error messages 
    void clearErrorLabels() { 
        lblErrorPatientId.setText("");
        lblErrorPatientId.setVisible(false);
        lblErrorMedicineId.setText("");
        lblErrorMedicineId.setVisible(false);
        lblErrorDosePerDay.setText("");
        lblErrorDosePerDay.setVisible(false);
    }

    // validate all user entry before sending new patient details to DB
    boolean isValidData() throws SQLException {
        clearErrorLabels();
        boolean result = true; 
        
        String field_hospital_id = cmbPatientId.getSelectedItem().toString();
        String field_doctor_ssn = cmbMedicineId.getSelectedItem().toString();
        String field_dose_per_day = txtDosePerDay.getText().trim();
            
        if (!isInteger(field_dose_per_day)) {
            lblErrorDosePerDay.setText("Doses per day should be a number");
            lblErrorDosePerDay.setVisible(true);
            result = false;
        }

        if (field_dose_per_day.isEmpty()) {
            lblErrorDosePerDay.setText("Cannot be empty");
            lblErrorDosePerDay.setVisible(true);
            result = false;
        }

        return result;
    }

    // clear for every new entry 
    void clearInputBoxes() { 
        cmbPatientId.setSelectedIndex(0);
        cmbMedicineId.setSelectedIndex(0);
        txtDosePerDay.setText("");
    }
    
    private void btnAddNewEmpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewEmpActionPerformed
        // TODO add your handling code here:

        try {
            if (isValidData()) {
                String field_patient_id = cmbPatientId.getSelectedItem().toString();
                String field_medicine_id = cmbMedicineId.getSelectedItem().toString();
                String field_doses_per_day = txtDosePerDay.getText().trim();

                String prepSQL = "INSERT INTO takes (patient_id, medicine_id, doses_per_day) VALUES ("
                        + "'" + field_patient_id + "', "
                        + "" + field_medicine_id + ", "
                        + "'" + field_doses_per_day + "' "
                        + ")";
                System.out.println("[INSERT Takes] " + prepSQL);

                int result = dbCon.executePrepared(prepSQL);
                if (result > 0) {
                    javax.swing.JLabel label = new javax.swing.JLabel("New take added successfully.");
                    label.setFont(new java.awt.Font("Arial", java.awt.Font.BOLD, 18));
                    JOptionPane.showMessageDialog(null, label, "SUCCESS", JOptionPane.INFORMATION_MESSAGE);
                    clearInputBoxes();
                }

                rs.close();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error adding new take.");
        }
    }//GEN-LAST:event_btnAddNewEmpActionPerformed

    private void cmbMedicineIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbMedicineIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbMedicineIdActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewEmp;
    private javax.swing.JComboBox<String> cmbMedicineId;
    private javax.swing.JComboBox<String> cmbPatientId;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel lblErrorDosePerDay;
    private javax.swing.JLabel lblErrorMedicineId;
    private javax.swing.JLabel lblErrorPatientId;
    private javax.swing.JTextField txtDosePerDay;
    // End of variables declaration//GEN-END:variables
}
