/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package jdbcgui;


public class Menu extends javax.swing.JFrame {

    LoginUser luser; // the login user details are obtained from the Login form

    /**
     * Creates new form Menu
     */
    
    LoginUser loggedUser;
    
    public Menu(LoginUser user) {
        initComponents();
        this.setLocationRelativeTo(null); // center form in screen 

        luser = user; // user details are obtained from the Login form and passed to constructor of Menu form object
        if (user.type == 1) { // hide the user management menu if the logged in user is NOT administrator 
            menuUser.setVisible(false);
            
        }
        
        loggedUser = user;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jLabel1 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuLogout = new javax.swing.JMenuItem();
        menuExit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuAddHospital = new javax.swing.JMenuItem();
        menuUpdateHospital = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuAddEmployee = new javax.swing.JMenuItem();
        menuUpdateEmployee = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        menuAddPatient = new javax.swing.JMenuItem();
        menuUpdatePatient = new javax.swing.JMenuItem();
        menuPatientStats = new javax.swing.JMenuItem();
        menuUser = new javax.swing.JMenu();
        menuAddUser = new javax.swing.JMenuItem();
        menuUpdateUser = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        menuAddMedicine = new javax.swing.JMenuItem();
        menuUpdateMedicine = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        menuAddDisease = new javax.swing.JMenuItem();
        menuUpdateDisease = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        menuAddCure = new javax.swing.JMenuItem();
        menuUpdateCure = new javax.swing.JMenuItem();
        jMenu10 = new javax.swing.JMenu();
        menuAddTakes = new javax.swing.JMenuItem();
        menuUpdateTakes = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu - JDBC GUI");
        setResizable(false);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcgui/employees.jpg"))); // NOI18N

        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N

        jMenu1.setText("File");
        jMenu1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuLogout.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuLogout.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcgui/logout.png"))); // NOI18N
        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        jMenu1.add(menuLogout);

        menuExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuExit.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jdbcgui/close.png"))); // NOI18N
        menuExit.setText("Exit");
        menuExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuExitActionPerformed(evt);
            }
        });
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Hospital");
        jMenu2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuAddHospital.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuAddHospital.setText("Add New Hospital");
        menuAddHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddHospitalActionPerformed(evt);
            }
        });
        jMenu2.add(menuAddHospital);

        menuUpdateHospital.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuUpdateHospital.setText("Update/Delete Hospital");
        menuUpdateHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateHospitalActionPerformed(evt);
            }
        });
        jMenu2.add(menuUpdateHospital);

        jMenuBar1.add(jMenu2);

        jMenu5.setText("Employee");
        jMenu5.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuAddEmployee.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuAddEmployee.setText("Add New Employee");
        menuAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddEmployeeActionPerformed(evt);
            }
        });
        jMenu5.add(menuAddEmployee);

        menuUpdateEmployee.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuUpdateEmployee.setText("Update/Delete Employee");
        menuUpdateEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateEmployeeActionPerformed(evt);
            }
        });
        jMenu5.add(menuUpdateEmployee);

        jMenuBar1.add(jMenu5);

        jMenu6.setText("Patient");
        jMenu6.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuAddPatient.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuAddPatient.setText("Add New Patient");
        menuAddPatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddPatientActionPerformed(evt);
            }
        });
        jMenu6.add(menuAddPatient);

        menuUpdatePatient.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuUpdatePatient.setText("Update/Delete Patient");
        menuUpdatePatient.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdatePatientActionPerformed(evt);
            }
        });
        jMenu6.add(menuUpdatePatient);

        menuPatientStats.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuPatientStats.setText("View Patient Info");
        menuPatientStats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPatientStatsActionPerformed(evt);
            }
        });
        jMenu6.add(menuPatientStats);

        jMenuBar1.add(jMenu6);

        menuUser.setText("User");
        menuUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuAddUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuAddUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuAddUser.setText("Add New User");
        menuAddUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddUserActionPerformed(evt);
            }
        });
        menuUser.add(menuAddUser);

        menuUpdateUser.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        menuUpdateUser.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuUpdateUser.setText("Update/Delete User");
        menuUpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateUserActionPerformed(evt);
            }
        });
        menuUser.add(menuUpdateUser);

        jMenuBar1.add(menuUser);

        jMenu7.setText("Medicine");
        jMenu7.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuAddMedicine.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuAddMedicine.setText("Add New Medicine");
        menuAddMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddMedicineActionPerformed(evt);
            }
        });
        jMenu7.add(menuAddMedicine);

        menuUpdateMedicine.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuUpdateMedicine.setText("Update/Delete Medicine");
        menuUpdateMedicine.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateMedicineActionPerformed(evt);
            }
        });
        jMenu7.add(menuUpdateMedicine);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Disease");
        jMenu8.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuAddDisease.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuAddDisease.setText("Add New Disease");
        menuAddDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddDiseaseActionPerformed(evt);
            }
        });
        jMenu8.add(menuAddDisease);

        menuUpdateDisease.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuUpdateDisease.setText("Update/Delete Disease");
        menuUpdateDisease.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateDiseaseActionPerformed(evt);
            }
        });
        jMenu8.add(menuUpdateDisease);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Cures");
        jMenu9.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuAddCure.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuAddCure.setText("Add New Cure");
        menuAddCure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddCureActionPerformed(evt);
            }
        });
        jMenu9.add(menuAddCure);

        menuUpdateCure.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuUpdateCure.setText("Delete Cure");
        menuUpdateCure.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateCureActionPerformed(evt);
            }
        });
        jMenu9.add(menuUpdateCure);

        jMenuBar1.add(jMenu9);

        jMenu10.setText("Takes");
        jMenu10.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N

        menuAddTakes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuAddTakes.setText("Add New Take");
        menuAddTakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAddTakesActionPerformed(evt);
            }
        });
        jMenu10.add(menuAddTakes);

        menuUpdateTakes.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        menuUpdateTakes.setText("Update/Delete Take");
        menuUpdateTakes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuUpdateTakesActionPerformed(evt);
            }
        });
        jMenu10.add(menuUpdateTakes);

        jMenuBar1.add(jMenu10);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuAddHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddHospitalActionPerformed
        // TODO add your handling code here:
        (new AddHospital()).setVisible(true);
    }//GEN-LAST:event_menuAddHospitalActionPerformed

    private void menuUpdateHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateHospitalActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteHospital()).setVisible(true);

    }//GEN-LAST:event_menuUpdateHospitalActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        // TODO add your handling code here:
        (new LoginForm()).setVisible(true);
        this.dispose(); // the Menu form is disposed ONLY when the currently logged in user logs out
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuExitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuExitActionPerformed

    private void menuAddUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddUserActionPerformed
        // TODO add your handling code here:
        (new AddNewLoginUser()).setVisible(true);
    }//GEN-LAST:event_menuAddUserActionPerformed

    private void menuUpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateUserActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteLoginUser(loggedUser)).setVisible(true);
    }//GEN-LAST:event_menuUpdateUserActionPerformed

    private void menuAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddEmployeeActionPerformed
        // TODO add your handling code here:
        (new AddEmployee()).setVisible(true);
    }//GEN-LAST:event_menuAddEmployeeActionPerformed

    private void menuUpdateEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateEmployeeActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteEmployee()).setVisible(true);
    }//GEN-LAST:event_menuUpdateEmployeeActionPerformed

    private void menuAddPatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddPatientActionPerformed
        // TODO add your handling code here:
        (new AddPatient()).setVisible(true);
    }//GEN-LAST:event_menuAddPatientActionPerformed

    private void menuUpdatePatientActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdatePatientActionPerformed
        // TODO add your handling code here:
        (new UpdateDeletePatient()).setVisible(true);
    }//GEN-LAST:event_menuUpdatePatientActionPerformed

    private void menuPatientStatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPatientStatsActionPerformed
        // TODO add your handling code here:
        (new StatsPatient()).setVisible(true);
    }//GEN-LAST:event_menuPatientStatsActionPerformed

    private void menuAddMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddMedicineActionPerformed
        // TODO add your handling code here:
        (new AddMedicine()).setVisible(true);
    }//GEN-LAST:event_menuAddMedicineActionPerformed

    private void menuUpdateMedicineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateMedicineActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteMedicine()).setVisible(true);
    }//GEN-LAST:event_menuUpdateMedicineActionPerformed

    private void menuAddDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddDiseaseActionPerformed
        // TODO add your handling code here:
        (new AddDisease()).setVisible(true);
    }//GEN-LAST:event_menuAddDiseaseActionPerformed

    private void menuUpdateDiseaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateDiseaseActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteDisease()).setVisible(true);
    }//GEN-LAST:event_menuUpdateDiseaseActionPerformed

    private void menuAddCureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddCureActionPerformed
        // TODO add your handling code here:
        (new AddCure()).setVisible(true);
    }//GEN-LAST:event_menuAddCureActionPerformed

    private void menuUpdateCureActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateCureActionPerformed
        // TODO add your handling code here:
        (new DeleteCure()).setVisible(true);
    }//GEN-LAST:event_menuUpdateCureActionPerformed

    private void menuAddTakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAddTakesActionPerformed
        // TODO add your handling code here:
        (new AddTakes()).setVisible(true);
    }//GEN-LAST:event_menuAddTakesActionPerformed

    private void menuUpdateTakesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuUpdateTakesActionPerformed
        // TODO add your handling code here:
        (new UpdateDeleteTake()).setVisible(true);
    }//GEN-LAST:event_menuUpdateTakesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu10;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuAddCure;
    private javax.swing.JMenuItem menuAddDisease;
    private javax.swing.JMenuItem menuAddEmployee;
    private javax.swing.JMenuItem menuAddHospital;
    private javax.swing.JMenuItem menuAddMedicine;
    private javax.swing.JMenuItem menuAddPatient;
    private javax.swing.JMenuItem menuAddTakes;
    private javax.swing.JMenuItem menuAddUser;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenuItem menuPatientStats;
    private javax.swing.JMenuItem menuUpdateCure;
    private javax.swing.JMenuItem menuUpdateDisease;
    private javax.swing.JMenuItem menuUpdateEmployee;
    private javax.swing.JMenuItem menuUpdateHospital;
    private javax.swing.JMenuItem menuUpdateMedicine;
    private javax.swing.JMenuItem menuUpdatePatient;
    private javax.swing.JMenuItem menuUpdateTakes;
    private javax.swing.JMenuItem menuUpdateUser;
    private javax.swing.JMenu menuUser;
    // End of variables declaration//GEN-END:variables
}
